alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: owid-datasette
region: fra
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: owid/owid-datasette
  http_port: 8001
  instance_count: 1
  name: owid-datasette
  routes:
  - path: /
  dockerfile_path: Dockerfile